[Export]
baked_state = false
offer_binder = true
slider_server_url="https://pluto-deploy.herokuapp.com/"
ignore_cache = []
create_index = false

[SliderServer]
host = "0.0.0.0"
port = 1234
exclude=[
    # these are in the repo but not used on the website
]
